In [1]:
import numpy as np

### 1. Boolean Indexing

In [2]:
arr = np.arange(3)

In [3]:
arr

array([0, 1, 2])

In [4]:
selector = [True, False, True]

In [5]:
arr[selector]

array([0, 2])

In [7]:
arr2 = np.arange(1,11)

In [8]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr2 > 7

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [10]:
arr2[arr2 > 7]

array([ 8,  9, 10])

In [12]:
arr2[(arr2>2) & (arr2<7)]    # &, |, ~ # and, or, not

array([3, 4, 5, 6])

### 3. Arthimetic operations and functions

In [14]:
a = np.arange(1,11)
b = np.arange(1,11)

In [15]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
a + b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [18]:
a - b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
b / a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
a * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [21]:
np.add(a, b)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [22]:
np.subtract(a,b)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.multiply(a, b)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [24]:
np.mod(a, b)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [26]:
# broadcasting
a = np.arange(1,10).reshape(3,3)

In [27]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
b = np.arange(1,4)

In [29]:
b

array([1, 2, 3])

In [30]:
a + b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])