In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [3]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

arr1[0,0]

In [6]:
arr1[1,-1]

10

In [7]:
arr1.ndim

2

In [10]:
arr2 = np.array([[[1,2,3],[6,7,8]],[[9,10,11],[12,13,14]]])

In [11]:
arr2

array([[[ 1,  2,  3],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14]]])

In [12]:
arr2[1,1,2]

14

In [13]:
arr2[-1,-1,-1]

14

### 1. Using Bulit-in array creation functions

In [14]:
integers_array = np.arange(10)

In [15]:
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
second_arr = np.arange(100,130)

In [17]:
second_arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [18]:
third_arr = np.arange(100,151,2)

In [19]:
third_arr

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150])

In [20]:
# floating point array - equally spaced
first_float_arr = np.linspace(10,20)   # by default, it will generate 50 numbers

In [21]:
first_float_arr

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [22]:
second_float_arr = np.linspace(10, 20, 5)

In [23]:
second_float_arr

array([10. , 12.5, 15. , 17.5, 20. ])

In [24]:
# random numbers
rand_arr = np.random.rand(10)

In [25]:
rand_arr

array([0.90995729, 0.18684201, 0.23949956, 0.95823749, 0.14020585,
       0.88248716, 0.0741773 , 0.10216348, 0.50263927, 0.89410582])

In [26]:
rand_arr = np.random.rand(4, 4)

In [27]:
rand_arr

array([[0.00962887, 0.45546244, 0.94101201, 0.77156599],
       [0.31274633, 0.32239166, 0.02653864, 0.08802259],
       [0.52322564, 0.95485252, 0.93534882, 0.52683514],
       [0.37587249, 0.06110117, 0.98247024, 0.8832277 ]])

In [28]:
rand_int_arr = np.random.randint(0, 100, 20)

In [29]:
rand_int_arr

array([76, 10, 49, 66, 98, 48, 52, 50, 95, 74, 92, 81, 91, 18, 76, 22, 94,
       11, 45, 19])

### 2. Creating arrays with filled constants

In [30]:
first_arr = np.zeros(5)

In [31]:
first_arr

array([0., 0., 0., 0., 0.])

In [32]:
second_zeros_arr = np.zeros((5, 10))

In [33]:
second_zeros_arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
first_ones_arr = np.ones((5,10), dtype=np.int8)

In [36]:
first_ones_arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

In [37]:
first_arr = np.full(5, 10)

In [38]:
first_arr

array([10, 10, 10, 10, 10])

In [39]:
second_arr = np.full((2,2), 20)

In [40]:
second_arr

array([[20, 20],
       [20, 20]])

### 3. Finding the size and shape of an array

In [41]:
second_arr.shape

(2, 2)

In [42]:
arr2 = np.arange(1,13).reshape(2,6)

In [43]:
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [44]:
np.size(arr2)

12

### 4. Adding, removing, and sorting elements

In [45]:
first_arr = np.array([1,2,3,5])

In [46]:
new_first_arr = np.insert(first_arr, 3, 4)

In [47]:
new_first_arr

array([1, 2, 3, 4, 5])

In [48]:
new_first_arr = np.append(new_first_arr, 6)

In [49]:
new_first_arr

array([1, 2, 3, 4, 5, 6])

In [50]:
delete_arr = np.delete(new_first_arr, 5)

In [51]:
delete_arr

array([1, 2, 3, 4, 5])

In [52]:
integers_arr = np.random.randint(0, 20, 20)

In [53]:
integers_arr

array([12,  4, 15,  3, 13, 13,  1,  7,  6, 19,  3,  0,  7,  7, 16,  6,  9,
        9, 15,  5])

In [54]:
np.sort(integers_arr)

array([ 0,  1,  3,  3,  4,  5,  6,  6,  7,  7,  7,  9,  9, 12, 13, 13, 15,
       15, 16, 19])

In [55]:
arr_id = np.arange(10)

In [56]:
arr_id

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr_id[:2]

array([0, 1])

In [58]:
arr_id[2:6]

array([2, 3, 4, 5])

In [59]:
arr_id[6:]

array([6, 7, 8, 9])

In [60]:
arr_id[::2]

array([0, 2, 4, 6, 8])